targets:
  $default:
    sources:
      - "src/**"
      - "lib/**"
    builders:
      build_node_compilers|entrypoint:
        generate_for:
          - "src/**.dart"
        options:
          compiler: dartdevc
