name: node_bind
# version: 1.0.4
# author: Javier Lecuona <javierlecuona@gmail.com>
# description: A library that generates Dart classes (parse and generator included) from a json string.
# homepage: https://github.com/javiercbk/json_to_dart
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  js: ^0.6.1
  # json_ast: "^1.0.5"
  json_to_dart: ^1.0.4
  node_interop: ^1.0.3
  # convert: "^2.0.1"

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.0.0
  node_preamble: ^1.4.8
  # build_node_compilers: ^0.2.0
  cli_pkg: ^1.0.0-beta.6
  grinder: ^0.8.4
  source_gen: ^0.9.4
  todo_reporter_generator:
    path: ../todo_reporter.dart/todo_reporter_generator/


  build_test:

  # build_runner: ^1.9.0
  # build_test: ^0.10.2
  # # build_web_compilers: ^2.6.1
  # build_node_compilers: ^0.2.4

